name: Generate pacman animation

on:
  schedule:
    # Runs at 00:00 and 12:00 UTC every day
    - cron: "0 0,12 * * *" 
  
  workflow_dispatch: # Allows manual trigger from the Actions tab

  push:
    branches:
    - main # Trigger on push to main branch

jobs:
  generate:
    # IMPORTANT: The token needs write access to the contents of the repo.
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 1. Generate the SVG image using the action
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main 
        with:
          # Uses your GitHub username detected automatically
          github_user_name: ${{ github.repository_owner }}
      
      # 2. Commit and Push the generated SVG file back to the 'main' branch
      - name: Commit and Push Pacman Graph
        uses: EndBug/add-and-commit@v9 
        with:
          message: "chore: Updated Pac-Man Contribution Graph"
          # Commits both the dark and light mode SVG files
          add: 'pacman-contribution-graph*.svg' 
